#!/bin/bash

declare -A cmdignore

cmdignore[htop]=1
cmdignore[tmux]=1
cmdignore[top]=1
cmdignore[vim]=1

preexec() {
	cmd=$1
	cmd_basename=${cmd%% *}
	cmd_start=`date +%s`
}

precmd() {
	retval=$?
	cmd_end=`date +%s`
	if [ -z "$cmd" ] ; then
		return
	fi
	if [ "x${cmdignore[$cmd_basename]}" == "x1" ]; then
		return
	fi
	if [ $retval -gt 0 ]; then
		cmdstat="with warning"
	else
		cmdstat="successfully"
	fi
	urgency="critical"
	DIFF=`expr ${cmd_end} - ${cmd_start}`
	if [ $DIFF -gt 10 ]; then
		if [ ! -z $SSH_TTY ]; then
			notify-send -i utilities-terminal -u $urgency "$cmd_basename on `hostname` completed $cmdstat" "\"$cmd\" took ${DIFF}s"
		else
			notify-send -i utilities-terminal -u $urgency "$cmd_basename completed $cmdstat" "\"$cmd\" took ${DIFF}s"
		fi
		unset cmd
	fi
}
